### ISSUE TITLE
Windows detects trojan Wacatac.B!ml in Release 2.6

### ISSUE THREAD

**Issue by jose-carmona-villegas** [millerscout/Kenshi-Mod-Manager#1274]
Windows detects trojan Wacatac.B!ml in Release 2.6 (FullRelease.zip):

![image](https://user-images.githubusercontent.com/3709181/230803646-3635cfac-66ab-421c-8985-d085276243d9.png)
(Sorry but my Windows is in Spanish).
The file is immediately quarantined and removed.

**Comment by millerscout** [comment]
i don't mind the language 😉 

Both 
Standalone
https://www.virustotal.com/gui/file/ab285229591ed055eb426fa2da59b37dd20e52d2a0e4ae64c5e6f3c6e796ac74
and

FullRelease 
https://www.virustotal.com/gui/file/83568546a6b6097c1567de65804b131f6571b8b5b829a4ed9aad14f2947ba15f

are clean using https://www.virustotal.com/

you may check : [makeuseof](https://www.makeuseof.com/windows-wacatac-trojan/#:~:text=ml%20Trojan%3F-,The%20Wacatac.,data%20infection%2C%20and%20financial%20loss.)

**Comment by millerscout** [comment]
i'm currently reviewing the changes, but haven't noticed anything, strange on the latest release

https://github.com/millerscout/Kenshi-Mod-Manager/pull/1237/files

**Comment by jose-carmona-villegas** [comment]
I've tried again and now Windows is not quarantening the file. This is very weird.
I've had a recent update which may have fixed it so this is clearly a false positive.
I'm sorry for wasting your time. Thanks for your good work!
