### ISSUE TITLE
Mod Conflict Manager does nothing.

### ISSUE THREAD

**Issue by guaranteeofpain** [millerscout/Kenshi-Mod-Manager#20]
Mod Conflict manager opens for a moment(command prompt) and closes immediately with no errors or something.
My specs:
Win 10 pro build 18362.19h1_release.190318-1202 version 1909 x64
Cpu xeon E5-2670 (2 cpus)
96gb ram
Geforce gtx 1070 8gb
Motherboard Asus z9ped16\2l
Kenshi steam version, located on D drive, ssd.
I hope it hepls.

**Comment by millerscout** [comment]
what version you're currently using? 
there's any logs on folder that you may provide?
