### ISSUE TITLE
 When I click the mod tool exe it loads then nothing happens. Was working before.

### ISSUE THREAD

**Issue by E-Gamma-102** [millerscout/Kenshi-Mod-Manager#22]
I don't know what happened it was working and I didn't even update it to the new release it just stopped working out of nowhere. When I downloaded the latest release the same thing happens. I've tried running the windows compatibility checker and go with its recommended settings as well but that didn't work either. Any help or suggestions is greatly appreciated.I also tried running it as administrator but it asks if I'm sure then does nothing.

**Comment by Midaychi** [comment]
Close down the mod manager, head over to AppData\Local\Temp and delete the .net folder, then try again?

**Comment by millerscout** [comment]
@E-Gamma-102 what version you''re currently using?

recommend using the latest version on a fresh folder

**Comment by E-Gamma-102** [comment]
> 
> 
> Close down the mod manager, head over to AppData\Local\Temp and delete the .net folder, then try again?

Yep that fixed it. Thanks!
