### ISSUE TITLE
Misleading bug in show conflict feature: wrong "This value will be used"

### ISSUE THREAD

**Issue by bnn1** [millerscout/Kenshi-Mod-Manager#621]
Hello there. I've been using ur tool for some time and I can say it's great for mod managing, better than Kenshi launcher

But I found Show conflicts feature to be confusing and misleading: 
<details>
  <summary>bug image</summary>

  ![bug_or_feature](https://user-images.githubusercontent.com/55663639/141171513-fbc92729-b0f2-493e-afa4-87e8c9589f38.png)

</details>

So basically your tool tells me that mod placed above will override mod placed below which is untrue (according to [Atlas' guide to load order](https://steamcommunity.com/sharedfiles/filedetails/?id=1850250979) and common sense).  

Also, a question-suggestion, is it possible to make sort based on mod files overrides (and maybe Atlas' guide)?

**Comment by Tkdmaster** [comment]
Also came across this quirk/issue. The ordering is generally right, but the text given in the conflict feature is opposite to what it should be. confirmed this by switching the order of Advanced Training and a patch mod for it to what conflict feature recommended (patch would get the "loaded" info text) and tried to launch, only to get the main game launcher saying there was an issue, switching them back to having the patch after and the text saying the main mod's values would get used fixed it and also the patched values were used ingame.
