### ISSUE TITLE
Unhandled exception occurred: Sequence contains no elements

### ISSUE THREAD

**Issue by ganell** [millerscout/Kenshi-Mod-Manager#674]
![1](https://user-images.githubusercontent.com/97455572/148782370-4f7b31fc-5e61-42b5-ae3f-12cf9c183641.PNG)
Help

**Comment by OptimusGnarkill** [comment]
Having the same exact problem :( You figure it out yet?

**Comment by normnom** [comment]
I think I have a solution! What I did was validate the Integrity of kenshi though steam.  The I deleted the mod manager completely. Reinstalled it and it worked fine. I also unsubbed from most of my mods and resubbed. Try that.
